# fly.toml app configuration file generated for assistant-api on 2025-05-14T17:46:40-03:00
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = 'assistant-api'
primary_region = 'eze'

[build]
  dockerfile = 'Dockerfile'

[env]
  DATABASE_URL = '/mnt/assistant_data/db.sqlite'
  NODE_ENV = 'production'
  PORT = '3000'

[[mounts]]
  source = 'assistant_data'
  destination = '/mnt/assistant_data'
  initial_size = '2gb'

[http_service]
  internal_port = 3000
  force_https = true
  auto_stop_machines = 'stop'
  auto_start_machines = true
  min_machines_running = 1

[[vm]]
  memory = '2gb'
  cpu_kind = 'shared'
  cpus = 1
